# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rc_ZShRciR7I_seFgywM5wSWxMOc2ZCh
"""

!pip install nltk scikit-learn

import pandas as pd
import nltk
import re

from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

data = {
    "review": [
        "I love this product",
        "This is the worst experience ever",
        "Very good quality and fast delivery",
        "I am extremely disappointed",
        "Excellent service and friendly staff",
        "Poor quality and bad support",
        "Amazing experience",
        "Not worth the money"
    ],
    "sentiment": [1, 0, 1, 0, 1, 0, 1, 0]  # 1=Positive, 0=Negative
}

df = pd.DataFrame(data)
df

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    words = text.split()
    words = [word for word in words if word not in stop_words]
    return " ".join(words)

df["clean_review"] = df["review"].apply(clean_text)
df

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["clean_review"])
y = df["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

new_text = ["The product quality is amazing"]
cleaned = [clean_text(new_text[0])]
vectorized = vectorizer.transform(cleaned)

prediction = model.predict(vectorized)
print("Sentiment:", "Positive" if prediction[0] == 1 else "Negative")